apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventstore.fullname" . }}
  labels:
    {{- include "eventstore.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "eventstore.selectorLabels" . | nindent 4 }}
