apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventstore.fullname" . }}-headless
  labels:
    {{- include "eventstore.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "eventstore.selectorLabels" . | nindent 4 }}
  ports:
    - port: 2113
      name: http
    - port: 1112
      name: tcp