apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-account.fullname" $ }}
data:
  ASPNETCORE_HTTP_PORTS: "5190"
  ASPNETCORE_HTTPS_PORTS: "7280"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/certs/tls.crt"
  ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/app/certs/tls.key"