apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-account.fullname" . }}
  labels:
    {{- include "kafka-account.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: https
    port: 7280
    targetPort: https
    nodePort: 31099
  selector:
    {{- include "kafka-account.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.component.sender }}
