version: '3'
services:
    es:
        container_name: es
        image: eventstore/eventstore
        ports:
            - "9011:2113"
            - "4011:1113"
        environment:
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_DISABLE_HTTP_CACHING=true
    cs:
        container_name: cs
        image: eventstore/eventstore
        ports:
            - "9016:2113"
            - "4016:1113"
        environment:
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_DISABLE_HTTP_CACHING=true
    ld:
        container_name: ld
        image: eventstore/eventstore
        ports:
            - "9012:2113"
            - "4012:1113"
        environment:
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_DISABLE_HTTP_CACHING=true
    lg:
        container_name: lg
        image: eventstore/eventstore
        ports:
            - "9013:2113"
            - "4013:1113"
        environment:
            - EVENTSTORE_DISABLE_HTTP_CACHING=true