version: '3'
services:
    es:
        container_name: es
        image: eventstore/eventstore
        ports:
            - "9011:2113"
            - "4011:1113"
        environment:
            - EVENTSTORE_DISABLE_HTTP_CACHING=true
            - EVENTSTORE_DEV=true
    cs:
        container_name: cs
        image: eventstore/eventstore
        ports:
            - "9016:2113"
            - "4016:1113"
        environment:
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_DISABLE_HTTP_CACHING=true
            - EVENTSTORE_DEV=true