services:
  kafka1: &template
    image: bitnami/kafka
    container_name: broker1
    restart: always
    env_file:
      - kafka.env
    environment: &env
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9192
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092,EXTERNAL://localhost:9192
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@broker1:9093,2@broker2:9093,3@broker3:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_MESSAGE_MAX_BYTES: 1048588
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: 2147483647
      KAFKA_CFG_NUM_PARTITIONS: 1
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
    ports:
      - 9192:9192
    volumes:
      - ./kafka/broker1:/bitnami/kafka:rw

  kafka2:
    <<: *template
    container_name: broker2
    environment:
      <<: *env
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9292
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092,EXTERNAL://localhost:9292
    ports:
      - 9292:9292
    volumes:
      - ./kafka/broker2:/bitnami/kafka:rw

  kafka3:
    <<: *template
    hostname: broker3
    container_name: broker3
    environment:
      <<: *env
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9392
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092,EXTERNAL://localhost:9392
    ports:
      - 9392:9392
    volumes:
      - ./kafka/broker3:/bitnami/kafka:rw

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1:9092,broker2:9092,broker3:9092
    ports:
      - 9091:8080
    volumes:
      - ./kafka/kafka_ui/etc/localtime:/etc/localtime
