// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Domain")>]
[<assembly: AssemblyDescriptionAttribute("Lightweight framework for CQRS")>]
[<assembly: AssemblyProductAttribute("UniStream")>]
[<assembly: AssemblyCompanyAttribute("Eric")>]
[<assembly: AssemblyVersionAttribute("0.8.2")>]
[<assembly: AssemblyFileVersionAttribute("0.8.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.8.2")>]
[<assembly: InternalsVisibleToAttribute("Note.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Domain"
    let [<Literal>] AssemblyDescription = "Lightweight framework for CQRS"
    let [<Literal>] AssemblyProduct = "UniStream"
    let [<Literal>] AssemblyCompany = "Eric"
    let [<Literal>] AssemblyVersion = "0.8.2"
    let [<Literal>] AssemblyFileVersion = "0.8.2"
    let [<Literal>] AssemblyInformationalVersion = "0.8.2"
    let [<Literal>] InternalsVisibleTo = "Note.Tests"
