services:
  ca:
    image: eventstore/es-gencert-cli
    container_name: ca
    entrypoint: bash
    user: "1000:1000"
    command: >
      -c "mkdir -p ./certs
      && cd /certs
      && es-gencert-cli create-ca
      && find . -type f -print0 | xargs -0 chmod 666"
    volumes:
      - ./certs:/certs
