apiVersion: v1
kind: Service
metadata:
  name: esdb-headless
spec:
  clusterIP: None
  selector:
    app: esdb
  ports:
    - name: http
      port: 2113
      targetPort: 2113
    - name: tcp
      port: 1113
      targetPort: 1113
