apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esdb
spec:
  serviceName: esdb-headless
  replicas: 3
  selector:
    matchLabels:
      app: esdb
  template:
    metadata:
      labels:
        app: esdb
    spec:
      initContainers:
        - name: init-certs
          image: busybox
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              set -ex
              CERT_DIR=/etc/eventstore/certs
              mkdir -p ${CERT_DIR}
              mkdir -p /usr/local/bin
              cp /etc/eventstore/cli/es-gencert-cli /usr/local/bin/
              es-gencert-cli create-node \
                --out ${CERT_DIR} \
                --ca-certificate /etc/eventstore/ca/ca.crt \
                --ca-key /etc/eventstore/ca/ca.key \
                --ip-addresses $(hostname -i) \
                --dns-names $(hostname),$(hostname).esdb-headless.default.svc.cluster.local
              find ${CERT_DIR} -type f -print0 | xargs -0 chmod 666
          volumeMounts:
            - name: certs
              mountPath: /etc/eventstore/certs
            - name: ca
              mountPath: /etc/eventstore/ca
            - name: cli
              mountPath: /etc/eventstore/cli
      containers:
        - name: esdb
          image: eventstore/eventstore
          imagePullPolicy: Never
          ports:
            - containerPort: 2113
              name: http
            - containerPort: 1113
              name: tcp
          envFrom:
            - configMapRef:
                name: esdb-config
          volumeMounts:
            - name: certs
              mountPath: /etc/eventstore/certs
            - name: ca
              mountPath: /etc/eventstore/ca
      volumes:
        - name: certs
          emptyDir: {}
        - name: ca
          secret:
            secretName: root-ca
        - name: cli
          persistentVolumeClaim:
            claimName: setup
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
