apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrent.fullname" . }}-headless
  labels:
    {{- include "kurrent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kurrent.selectorLabels" . | nindent 4 }}
  ports:
    - port: 2113
      name: http
    - port: 1112
      name: tcp