apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrent.fullname" $ }}-external
  labels:
    {{- include "kurrent.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 2113
    nodePort: 31088
  selector:
    {{- include "kurrent.selectorLabels" . | nindent 4 }}
