{{- $replicaCount := int .Values.replicaCount }}
{{- $nodePortBase := .Values.nodePortBase }}
{{- range $index := until $replicaCount }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrent.fullname" $ }}-{{ $index }}
  labels:
    {{- include "kurrent.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 2113
    nodePort: {{ add $nodePortBase $index }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "kurrent.fullname" $ }}-{{ $index }}
---
{{- end }}