apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kurrent-account.fullname" . }}
  labels:
    {{- include "kurrent-account.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "kurrent-account.labels" . | nindent 8 }}
    spec:
      containers:
        - name: kurrent-init
          image: kurrent-init:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Never