apiVersion: v1
kind: Service
metadata:
  name: {{ include "kurrent-account.fullname" . }}-headless
  labels:
    {{- include "kurrent-account.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kurrent-account.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ include "kurrent-account.fullname" . }}
